main: com.creadri.lazyroad.LazyRoad
version: 0.7.2
name: LazyRoad
description: Make roads as you walk
authors: [adreide, VeraLapsa]
website: http://www.creadri.com
commands:
  road:
    description: 'Make roads.'
    usage: |
      /<command>
      /<command> roadName [start count]
      /<command> stop
      /<command> undo
      /<command> straight
      /<command> up
      /<command> down
      /<command> normal
  bridge:
    description: 'Make bridges.'
    usage: |
      /<command>
      /<command> roadName pillarName [start count]
      /<command> stop
      /<command> undo
      /<command> straight
      /<command> up
      /<command> down
      /<command> normal
  tunnel:
    description: 'Make tunnels.'
    usage: |
      /<command>
      /<command> roadName [start count]
      /<command> stop
      /<command> undo
      /<command> straight
      /<command> up
      /<command> down
      /<command> normal
permissions:
  lazyroad.build:
    default: op
    description: Allows users to build roads, bridges and tunnels.